version: '3.7'
services:

  postgres:
    image: "postgres:11.5"
    volumes:
      - "meldeplikt-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test-user"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "meldeplikt"

volumes:
  meldeplikt-data: