version: '3.7'
services:

  postgres:
    image: "postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2"
    volumes:
      - "meldekortservice:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "meldekortservice-local"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "meldekortservice-local"

volumes:
  meldekortservice:
