version: '3.7'
services:

  postgres:
    image: "postgres:14-alpine"
    volumes:
      - "meldekortservice:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "meldekortservice-local"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "meldekortservice-local"

volumes:
  meldekortservice: