apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: meldekortservice
  namespace: ##NAMESPACE##
  labels:
    team: meldekort
spec:
  image: repo.adeo.no:5443/meldeplikt/meldekortservice:##RELEASE_VERSION##
  port: 8090
  ingresses:
    - https://meldekortservice##URL_NAMESPACE##.nais.##DOMAIN_NAME##
    - https://app##URL_NAMESPACE##.adeo.no/meldekortservice
    - https://meldekortservice##URL_NAMESPACE##.##CLUSTER##.nais.io
  liveness:
    path: /meldekortservice/internal/isAlive
    initialDelay: 10
  readiness:
    path: /meldekortservice/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/##VAULT_SERVICEUSER_ENV##/creds/meldekortservice##DB_NAMESPACE##-user
        mountPath: /secrets/dbuser/meldekortservicedbuser
      - kvPath: oracle/data/##VAULT_SERVICEUSER_ENV##/config/meldekortservice##DB_NAMESPACE##
        mountPath: /secrets/dbconf/meldekortservicedbconf
      - kvPath: serviceuser/data/##VAULT_SERVICEUSER_ENV##/srvmeldekortservice
        mountPath: /secrets/serviceuser/srvmeldekortservice
      - kvPath: serviceuser/data/##VAULT_SERVICEUSER_ENV##/srvsblarbeid
        mountPath: /secrets/serviceuser/srvsblarbeid
      - kvPath: kv/##VAULT_KV_ENV##/fss/meldekortservice/##NAMESPACE##
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/##VAULT_SERVICEUSER_ENV##/creds/meldekortservice
        mountPath: /var/run/secrets/nais.io/azuread
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 10
  webproxy: true
  resources:
    limits:
      cpu: '1'
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  envFrom:
    - configmap: loginservice-idporten

---
apiVersion: nais.io/v1
kind: Alert
metadata:
  name: meldekortservice
  namespace: default
  labels:
    team: meldekort
spec:
  receivers:
    slack:
      channel: '##SLACK_ALERT_CHANNEL##'
  alerts:
    - alert: meldekortservice_applikasjonsinstanser nede
      expr: kube_deployment_status_replicas_unavailable{deployment="meldekortservice"} > 0
      for: 2m
      description: >
            *{{ $labels.deployment }}* har utilgjengelige applikasjonsinstanser (podder) i *{{ $labels.namespace }}*
      action: >
            Kjør `kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for å se events,
            evt. kjør først `kubectl get pods -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for en oversikt over poddene.
            Sjekk også Kibana for eventuelle feil som er logget;
            query `application:{{ $labels.deployment }} AND namespace:{{ $labels.namespace }} AND (level:Error OR level:Warning)`.
      severity: danger
    - alert: meldekortservice_feil er logget
      expr: sum(increase(logd_messages_total{log_app="meldekortservice",log_level="Error"}[10m])) by (log_app, log_namespace) > 0
      for: 3m
      description: >
            *{{ $labels.log_app }}* har logget feil med loggnivå Error i *{{ $labels.log_namespace }}*
      action: >
            Antall feil målt over siste 10 minutter er *{{ $value }}*.
            Sjekk Kibana for detaljer om feil som er logget;
            query `application:{{ $labels.log_app }} AND namespace:{{ $labels.log_namespace }} AND (level:Error OR level:Warning)`.
      severity: danger