apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{reponame}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: navikt/{{reponame}}:{{version}}
  team: {{team}}
  port: 8090
  ingresses:
    - {{ingress1}}
    - {{ingress2}}
  liveness:
    path: {{baseurl}}/internal/isAlive
    initialDelay: 10
  readiness:
    path: {{baseurl}}/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceUserKvPath}}
        mountPath: /var/run/secrets/nais.io/srvmeldekortservice
      - kvPath: {{envVarKvPath}}
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 10
  webproxy: true
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      cpu: 300m
      memory: 1024Mi