apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ appName }}{{ dashEnv }}
  namespace: meldekort
  labels:
    team: meldekort
spec:
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "azp_name"
  image: {{image}}
  port: 8090
  prometheus:
    enabled: true
    path: /meldekortservice/internal/metrics
  secureLogs:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /meldekortservice/internal/isAlive
    initialDelay: 15
    timeout: 10
  readiness:
    path: /meldekortservice/internal/isReady
    initialDelay: 15
    timeout: 10
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/{{ vaultServiceuserEnv }}/creds/{{ appName }}{{ dbEnv }}-user
        mountPath: /secrets/dbuser/meldekortservicedbuser
      - kvPath: oracle/data/{{ vaultServiceuserEnv }}/config/{{ appName }}{{ dbEnv }}
        mountPath: /secrets/dbconf/meldekortservicedbconf
      - kvPath: serviceuser/data/{{ vaultServiceuserEnv }}/srvmeldekortservice
        mountPath: /secrets/serviceuser/srvmeldekortservice
      - kvPath: serviceuser/data/{{ vaultServiceuserEnv }}/srvsblarbeid
        mountPath: /secrets/serviceuser/srvsblarbeid
      - kvPath: kv/{{ vaultKvEnv }}/{{ appName }}{{ dashEnv }}/meldekort
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 50
  webproxy: true
  resources:
    limits:
      cpu: 1000m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:
    - name: IDPORTEN_ACCEPTED_AUDIENCE
      value: '{{ idportenAcceptedAudience }}'
    - name: TOKEN_X_ACCEPTED_AUDIENCE
      value: '{{ tokenxAcceptedAudience }}'
  idporten:
    enabled: true
  tokenx:
    enabled: true
