<?xml version="1.0" encoding="UTF-8"?>
<definitions 	xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:serv="http://www.aetat.no/amelding/externcontrolemelding/webservices"
                xmlns:ns1="http://www.aetat.no/arena/mk_meldekort.xsd"
                xmlns:ns2="http://www.aetat.no/arena/mk_meldekort_kontrollert.xsd"
                targetNamespace="http://www.aetat.no/amelding/externcontrolemelding/webservices">

    <!--
        On request by KES, the UsernameToken WS-Policy is moved to an external policy file, WEB-INF/usernametoken-policy.xml.
     -->

    <types>
        <xs:schema>
            <xs:import namespace="http://www.aetat.no/arena/mk_meldekort_kontrollert.xsd" schemaLocation="schemas/mk_meldekort_kontrollert.xsd"/>
            <xs:import namespace="http://www.aetat.no/arena/mk_meldekort.xsd" schemaLocation="schemas/mk_meldekort.xsd"/>
        </xs:schema>
    </types>

    <message name="CardControlRequest">
        <part name="meldekort" type="ns1:MeldekortType"/>
    </message>
    <message name="CardControlResponse">
        <part name="kontrollres" type="ns2:MeldekortKontrollertType"/>
    </message>

    <portType name="ExternControlEmeldingSOAP">
        <operation name="KontrollerEmeldingMeldekort">
            <input message="serv:CardControlRequest"/>
            <output message="serv:CardControlResponse"/>
        </operation>
    </portType>

    <binding name="ExternControlEmeldingBinding" type="serv:ExternControlEmeldingSOAP">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="KontrollerEmeldingMeldekort">
            <soap:operation soapAction="http://www.aetat.no/amelding/externcontrolemelding/webservices/KontrollerEmeldingMeldekortRequest"/>
            <input>
                <soap:body use="literal" namespace="http://www.aetat.no/amelding/externcontrolemelding/webservices" />
            </input>
            <output>
                <soap:body use="literal" namespace="http://www.aetat.no/amelding/externcontrolemelding/webservices" />
            </output>
        </operation>
    </binding>

    <service name="ExternControlEmelding">
        <port name="ExternControlEmeldingPort" binding="serv:ExternControlEmeldingBinding">
            <soap:address location="http://localhost/MeldekortFraEmelding/ExternControlEmelding"/>
        </port>
    </service>
</definitions>